name: Release

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  extract-tag:
    name: Extract release tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.RELEASE_TAG }}
      version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Parse refs
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          RELEASE_VERSION=$(echo "$RELEASE_TAG" | sed 's/^[^0-9]*//')
          echo "Detected version: $RELEASE_VERSION; Tag: $RELEASE_TAG"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

  build-release-debian:
    name: Build proxy package
    runs-on: ubuntu-22.04
    needs: ["extract-tag"]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'
      - name: Build package
        run: make -C cmd build-debian VERSION=${{ needs.extract-tag.outputs.version }}
      - name: Upload artifact
        run: gh release upload ${{ needs.extract-tag.outputs.tag }} cmd/.build/proxyd-debian-${{ needs.extract-tag.outputs.version }}-amd64.deb
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}

  build-and-publish-docker:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    needs: ["extract-tag"]
    env:
      REGISTRY: ghcr.io
      IMAGE_BASE_TAG: ghcr.io/${{ github.repository }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cmd/Dockerfile
          push: true
          tags: ${{ env.IMAGE_BASE_TAG }}:${{ needs.extract-tag.outputs.tag }}, ${{ env.IMAGE_BASE_TAG }}:latest
